import React from 'react';
import Head from 'next/head';
import s from '@/styles/Home.module.css';
import styled from 'styled-components';

const Title = styled.h1`
	padding: 4em;
	color: white;
	background-color: red;
`;

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={s.main}>
				<Title>Вика и Тёма</Title>
			</main>
		</>
	);
}
